EUDAT-B2NOTE/b2note

static/js/ontology-typeahead.js

Retrieve from Solr index and include as part of Typeahead menu entries alongside term label.

Ant1b #1 Display acronym and short form

---

searchapp/views.py
static/css/style.css
templates/searchapp/export.html

Indent json.dumps objects.
Use \<pre\> tag in html template.

Ant1b #10 indent exported json ld

---

.travis.yml
tests_tmp.py

Initial Travis CI job configuration, "hello world" type.

Ant1b #11 travis continuous integration

---

README.md

https://docs.travis-ci.com/user/status-images/

Embedding status images

---

README.md

According to EUDAT internal guidelines at: https://confluence.csc.fi/display/EUDAT2/On+Copyright+and+Licences.
Licence remains to be decided.

Ant1b #3 Readme copyright statement

---

.travis.yml
README.md
requirements.txt
semantic_indexer/SparqlOntoParser_main.py
semantic_indexer/solr_writer.py
tests_tmp.py

Edited and tested travis configuration file for unit tests already designed for django.

Pr #11 travis ci

---

b2note_app/mongo_support_functions.py
b2note_app/tests.py
b2note_app/views.py

Create annotation in two steps, add semantic tag or free text information, and the annotation itself.

Split-up create annotation function

---

b2note_app/views.py
static/css/bootstrap.css
static/js/utils.js
templates/b2note_app/interface_main.html

Added a new tab for creating free text annotations.

U.I. free text

---

b2note_api/b2note_api.py

This change must be undone for the production version.

Hard-coded url changed for pointing to the development version.

---

.gitignore
accounts/models.py
accounts/tests.py
accounts/views.py
b2note_app/models.py
b2note_devel/settings.py
requirements.txt

A new sqlite3 DB has been configured and a new app created for storing and managing simple user accounts.

New DB configured and models created for storing the user accounts.

---

accounts/backends.py
accounts/forms/__init__.py
accounts/forms/authenticate.py
accounts/forms/register.py
accounts/urls.py
accounts/views.py
b2note_devel/urls.py
templates/accounts/login.html
templates/accounts/register.html

State of code related to user authentication at the end of the code sprint.
URLs and forms, prototype states, unchecked.
Access to sqlite3 from views potentially non-functional.

Ant1b #45 register and login

---

accounts/backends.py
accounts/forms/authenticate.py
accounts/forms/register.py
accounts/models.py
accounts/urls.py
accounts/views.py
b2note_devel/settings.py
templates/accounts/profilepage.html
templates/accounts/register.html

Not completed, missing display of user information in profile page. And
review registration and login procedures for security flaws.

Access DB, register, login

---

accounts/backends.py
accounts/forms/register.py
accounts/models.py
accounts/views.py
templates/accounts/login.html
templates/accounts/profilepage.html
templates/accounts/register.html

Passing user_id from login view to profile page through sessions object.

Profile page with user information

---

accounts/forms/__init__.py
accounts/forms/profile.py
accounts/views.py
b2note_app/views.py
b2note_devel/urls.py
templates/b2note_app/profilepage.html

Profile page now part of b2note_app called from accounts app login view
upon successful login.

Session for login across apps

---

.gitignore
b2note_app/mongo_support_functions.py

CreateAnnotation function is called inside a try-except block.

CreateAnnotation function inside a try-except block.

---

b2note_app/mongo_support_functions.py

Occurrences in mongo_support_functions of type is unicode replaced by isinstance.

Check of unicode strings in mongo_support_functions improved

---

static/js/ontology-typeahead.js
templates/b2note_app/homepage.html

Rid of console interface within homepage.

Create from homepage

---

b2note_app/mongo_support_functions.py

Returns the list of annotations which match with the input or False if there is no matching annotations or an error is produced.

Function check duplicate annotation

---

b2note_app/mongo_support_functions.py

The CheckLengthFreeText function returns False either the length of the input is longer than the limit or an error has arised.

Function check length free text

---

accounts/forms/register.py
accounts/forms/reset_password.py
accounts/urls.py
accounts/views.py
b2note_devel/settings.py
templates/accounts/account_retrieve_email.html
templates/accounts/login.html
templates/accounts/password_reset_email.html
templates/accounts/password_reset_subject.txt
templates/accounts/profilepage.html
templates/accounts/request_account_retrieval.html
templates/accounts/test_template.html

Changes based on http://ruddra.com/2015/09/18/implementation-of-forgot-reset-password-feature-in-django/

Ant1b #76 reset password

---

b2note_devel/settings.py

Non local sqlite settings

---

b2note_app/mongo_support_functions.py

Call to SetAnnotationMotivation function mistakenly not uncommented.

Keyword motivation as tagging

---

b2note_app/tests.py
b2note_app/views.py

All previous tests working with latest code. Problem solved:
- Login and session keeping.
- Definition and inclusion of new variables passed by POST.
- Follow redirections.

Pr #120 unit tests

---

b2note_app/tests.py

Added comments to tests functions.

Pr #121 unit test internal links

---

b2note_app/views.py

Sorting works on local version but not server side.
Removing sorting for checking that everything else works as expected.
Is there a server side DB document that does not have a properly filled
“created” field?

Disable sorting annotation list on create time as test

---

b2note_app/views.py

Development version works with sorting disabled after Apache server
reload.
Re-enabling sorting on create datetime for testing after Apache reload
command…

Sorting annotation list fixing

---

accounts/views.py

Requires syncdb command executed server-side.

Trying server database save

---

b2note_app/mongo_support_functions.py
b2note_app/views.py
templates/b2note_app/edit_annotation.html
templates/b2note_app/export.html
templates/b2note_app/interface_main.html

All functionalities re-established.
Simple cases tested by hand.

Change model, adapt code

---

b2note_app/mongo_support_functions.py
b2note_app/views.py
templates/b2note_app/annotation_summary.html

Add 50px margin to allow scrolling down file list.
Information retrieved from reindexed Solr core.
Include list of reusing ontology acronyms.

Annotation summary page

---

b2note_devel/settings.py

Reverts EUDAT-B2NOTE/b2note#248. This change will be pull requested to the development branch first.

Revert "Debug disabled in settings."

---

b2note_api/b2note_api.py
b2note_api/jsonld_support_functions.py
b2note_api/settings.py
b2note_app/mongo_support_functions.py

http://b2note.bsc.es/api/export_to_triplestore

Update triplestore data API call

---

b2note_api/b2note_api.py

Server install of rdflib-jsonld library resulted in rdflib json-ld
processors (parser and serialiser) not readily associated to rdflib,
requires registering after importing modules.

Register json-ld processors

---

b2note_app/views.py

Update landing page file refs

---

b2note_api/b2note_api.py

Works, takes about 10s on current set of <50 annotations.
Speed would rather require that the graph be built incrementally on
local file, then loaded back in RAM for HTTP PUT current method to send
to triplestore.
One obstacle to doing this is avoiding blank node naming overlap across
individual increments generated graphs.
Requires identifying the method used by rdflib to attribute blank nodes
their identifiers, not yet achieved.

API call export_to_triplestore

---

b2note_app/mongo_support_functions.py
b2note_app/views.py
static/js/ontology-typeahead.js
templates/b2note_app/edit_annotation.html

Create annotation with the first returned class from Bloodhound

---

b2note_app/views.py
templates/b2note_app/searchresult.html

And let user display short or long form of the query string upon results page.

Search over multiple body sources

---

accounts/views.py
b2note_app/nav_support_functions.py
b2note_app/views.py
b2note_devel/urls.py
static/css/style.css
static/js/ontology-typeahead.js
static/js/utils.js
templates/accounts/feedback_page.html
templates/accounts/password_reset_email.html
templates/accounts/register.html
templates/accounts/request_account_retrieval.html
templates/accounts/reset_password.html
templates/b2note_app/__base.html
templates/b2note_app/allannotations.html
templates/b2note_app/help.html
templates/b2note_app/hostpage.html
templates/b2note_app/interface_main.html
templates/b2note_app/myannotations.html

take care of issues #305 to #314:
- password reset fix
- various UI upgrades

Aymrod #305 to #314

---

accounts/views.py
b2note_app/tests.py
templates/accounts/register.html
templates/captcha/text_field.html

Fix a crash that happens upon trying to register with already taken email or pseudonym, fix buggy display of the widget, remove autocompletion for captchas, add a test

AymRod_#316_RegisterCrashFix

---

b2note_app/tests.py

AymRod_#316_tryTests

---

accounts/client_credentials.json
accounts/tests.py
accounts/urls.py
accounts/views.py
templates/accounts/auth_main.html
templates/accounts/auth_redirected.html
templates/accounts/login.html
templates/accounts/old_login.html
templates/accounts/password_reset_email.html
templates/b2note_app/hostpage.html

testing b2access integration with pyoidc

pyoidc for b2access integration - still buggy

---

accounts/forms/register.py
accounts/views.py
templates/accounts/register.html

Registration and Signing in with B2Access should now work, for new accounts

AymRod_#329_OidcForNewAccounts

---

accounts/backends.py
accounts/client_credentials.json
accounts/forms/__init__.py
accounts/forms/register.py
accounts/tests.py
accounts/urls.py
accounts/views.py
b2note_app/nav_support_functions.py
b2note_app/views.py
templates/accounts/auth_main.html
templates/accounts/auth_redirected.html
templates/accounts/login.html
templates/accounts/old_login.html
templates/accounts/password_reset_email.html
templates/accounts/register.html
templates/b2note_app/help.html
templates/b2note_app/hostpage.html

The oidc flow should now work for all accounts

aymRod_#331_OidcCompleteForAllAccounts

---

accounts/forms/old_register.py
accounts/urls.py
templates/accounts/old_register.html

Now that we use B2Access, disable the old login and register functionalities

aymRod_#335_disableOldLoginAndRegister

---

templates/accounts/register.html
templates/b2note_app/_navigation.html
templates/b2note_app/hostpage.html
templates/b2note_app/interface_main.html

update hostpage
add ToU
remove pilot flag
update disclaimer
update feedback button

aymRod_#353_towardsProduction
